[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
svm_contracts = "DRZkDTej9HHkd8NgBdG76C4dFa3wFmbqBT7Sfd5kW7Ky"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
# Uncomment and set a custom RPC URL if needed:
# url = "https://solana-devnet.g.alchemy.com/v2/ZALGTmv2kBEwOrIwHgpuOvGiSfHca-wA"
# Or use a custom RPC provider:
# url = "https://your-custom-rpc-url.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
